---
- hosts: centos
  tasks:
    - name: add hostname to config
      lineinfile: 
        dest: /home/{{ansible_ssh_user}}/hostname.conf
        regexp: ^Hostname=.*
        insertafter:  ^# Hostname=
        line:  Hostname={{ ansible_hostname }}

