---
- hosts: centos_remote_a
  tasks: 
    - name: copy file to server
      copy: src=test.sh dest=/home/centos/test.sh mode=0755
    - name: Run the script
      command: /home/centos/test.sh 
      register:  comm_out
      ignore_errors: yes
    - debug: 
       msg= "STDOUT - {{ comm_out.stdout }}"
    - debug:
       msg="STDERR - {{ comm_out.stderr }}"
    - name: copy file to the server
      copy: src=version.txt dest=/home/{{ ansible_ssh_user }} mode=0755
    - name: Check version is present
      shell: cat /home/{{ ansible_ssh_user }}/version.txt | grep -q 4.16.2
      register: current_version
    - debug: msg= "STDOUT - {{ current_version.rc }}"