---
- name: format disk
  become: true
  hosts: localhost
  tasks:
    - name: get disk structure
      become: true
      command: fdisk -l
      register: get_disk
    - name: for debugging purpose
      debug:
        msg: " device : {{ get_disk.stdout | get_device }}"
    - name: test an empty list of device
      vars:
        device: "{{ get_disk.stdout | get_device }}"
      filesystem:
        fstype: ext4
        dev: "{{ item }}"
      when: device is defined 
      loop: "{{ device }}"